name: Docs CI

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/docs-ci.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.github/workflows/docs-ci.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: |
            {
              "config": {"default": true, "MD013": false }
            }

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --require-https --exclude-mail --accept 200,206,429 --verbose '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
